create database SIPOS;

use SIPOS;

create table USUARIO (
USER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
USER_NOME VARCHAR(60) NULL, 
USER_EMAIL VARCHAR(60) NOT NULL, 
USER_SENHA VARCHAR(32) NOT NULL, -- MD5
USER_RG VARCHAR(7),
USER_ORGAOEXPEDIDOR VARCHAR(5),
USER_CPF VARCHAR(11),
USER_ESTADOCIVIL VARCHAR(20),
USER_SEXO CHAR(1),
USER_NOMEMAE VARCHAR(60),
USER_NOMEPAI VARCHAR(60),
USER_DTNASCIMENTO DATE,
USER_NATURALIDADE VARCHAR(60),
USER_UF CHAR(2),
USER_PAIS VARCHAR(20),
USER_NACIONALIDADE VARCHAR(20),
-- RESIDENCIAL
USER_ENDERECO VARCHAR(200),
USER_CIDADE VARCHAR(40),
USER_CEP VARCHAR(9),
USER_UF_RESID CHAR(2),
USER_PAIS_RESID VARCHAR(20),
USER_TELEFONE_FIXO VARCHAR(11),
USER_CELULAR VARCHAR(11),
USER_DTCADASTRO TIMESTAMP,
USER_SITUACAO ENUM('PRECADASTRADO','ATIVO')
);


